version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "disabled"
    versioning-strategy: increase
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
    allow:
      - dependency-type: "direct"
